# Stage 1: Build the application
FROM maven:3.9.8-eclipse-temurin-21 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN echo "--- DEBUGGING: CHECKING VERSIONS ---" && java -version && mvn -version && echo "--- END DEBUGGING ---"
RUN mvn clean install -DskipTests

# Stage 2: Create the final production image
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Copy the JAR file from the builder stage
COPY --from=builder /app/target/*.jar app.jar

# Create a non-root user to run the application
RUN addgroup -S appgrp && adduser -S appuser -G appgrp
USER appuser

EXPOSE 8080
ENTRYPOINT ["java","-Xmx512m","-jar","app.jar"]
