version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: foodease:latest
    container_name: foodease-app
    volumes:
      - ~/.m2:/root/.m2
      - ./:/app
    command: mvn spring-boot:run -Dspring-boot.run.fork=false -Dspring-boot.run.profiles=dev
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://fe-mysql:3306/foodease?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_ELASTICSEARCH_URIS=http://fe-elasticsearch:9200
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - fe-mysql
      - fe-elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  fe-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?local=true | grep -E '\"status\":\"(green|yellow)\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  fe-mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=foodease
      - MYSQL_PASSWORD=123123
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=myuser
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  mysql-data:
  es-data:
  m2-cache:
