version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_prod
    image: ghcr.io/${GITHUB_REPOSITORY:-your-github-username/foodease}:${IMAGE_TAG:-latest}
    container_name: foodease-app-prod
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://fe-mysql:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - fe-mysql
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  fe-mysql:
    image: mysql:latest
    container_name: fe-mysql-prod
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  mysql-data:
  m2-cache:
