version: '3.8'

services:
  fe-mysql:
    image: mysql:latest
    container_name: foodease-mysql-local
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=foodease
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=123123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: 