version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_prod
    image: foodease-app
    container_name: foodease-app-prod
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://fe-mysql:3306/foodease?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=YOUR_MYSQL_PASSWORD_HERE
      - STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY_HERE
    ports:
      - "8080:8080"
    depends_on:
      fe-mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  fe-mysql:
    image: mysql:latest
    container_name: fe-mysql-prod
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_MYSQL_ROOT_PASSWORD_HERE
      - MYSQL_DATABASE=foodease
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=YOUR_MYSQL_PASSWORD_HERE
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "myuser", "-pYOUR_MYSQL_PASSWORD_HERE"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  mysql-data:
  m2-cache:
