server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: FoodEase

  datasource:
    url: jdbc:mysql://localhost:3306/foodease?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    rest:
      uris: http://fe-elasticsearch:9200

  docker:
    compose:
      enabled: false

  devtools:
    restart:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path : /swagger-ui.html
  api-docs:
    enabled: true
    path : /v3/api-docs
    groups:
      enabled: true
    version: openapi_3_0

jwt:
  valid-duration: 100000 # in second
  refreshable-duration: 100000 # in seconds

api:
  secret: 3d449436ff8b2668fde0409c7d01b1ad0eca19e7d39f7b8c59cbe979668795a1

stripe:
  api:
    key: sk_test_51Qg00nFl6JPDGnPVh6TosZpbfyyfoh0hQwuykM6xWJkHIgoJKk4YJDKzvWwubCVzLsv5UQm2ihe8FjyM3J0h0q6X00zIoJsUAl

logging:
  level:
    root: INFO
    com.foodease: DEBUG
    org.springframework.security: DEBUG
